version: "3.8"

services:
  backend:
    build: ./backend
    container_name: bakery-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - DB_HOST=postgres
      - DB_USER=bakeryuser
      - DB_PASSWORD=bakerypass
      - DB_NAME=bakerydb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
    networks:
      - bakery-network

  postgres:
    image: postgres:15
    container_name: bakery-db
    environment:
      POSTGRES_USER: bakeryuser
      POSTGRES_PASSWORD: bakerypass
      POSTGRES_DB: bakerydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - bakery-network

  redis:
    image: redis:alpine
    container_name: bakery-redis
    ports:
      - "6379:6379"
    networks:
      - bakery-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bakery-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"   # For communication with services
      - "15672:15672" # For RabbitMQ Web UI
    networks:
      - bakery-network

volumes:
  postgres_data:

networks:
  bakery-network:
    driver: bridge